### PR TITLE
Update south-african-journal-of-animal-science.csl

### PR DESCRIPTION
**Pull request by rmzelle**

### CODE REVIEW

**Comment by Yusufras** [comment]
I need to make some changes. I dont see the edit button when i open the style.
can you please assist.

**Comment by rmzelle** [comment]
You should be able to click the edit (pencil) icon at https://github.com/citation-style-language/styles/blob/master/south-african-journal-of-animal-science.csl

**Comment by Yusufras** [comment]
I have made some changes to the style but somehow it did not commit? Can you check please?

Vriendelike groete / Kind regards
Yusuf Ras

Fakulteitsbibliotekaris AgriWetenskappe / Faculty Librarian AgriSciences
Biblioteek- & Inligtingsdiens / Library & Information Service
Universiteit Stellenbosch University  | maphttps://www.google.co.za/maps/place/JS+Gericke+Library/@-33.932975,18.8640494,377m/data=!3m1!1e3!4m2!3m1!1s0x1dcdb25d82940c29:0x80f6dcd585958374 | Tel: +27 (021) 808 4345 | yr@sun.ac.zamailto:yr@sun.ac.za

**Comment by rmzelle** [comment]
@Yusufras, looking at your user activity (https://github.com/Yusufras?tab=activity), you did make a change twice, but you never created a pull request for either change.

I created a pull request for you at https://github.com/citation-style-language/styles/pull/2206. For the future, see https://help.github.com/articles/editing-files-in-another-user-s-repository/ and our instructions at https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3b-submitting-changes-to-an-existing-style to see how to make a pull request after making a change.

**Comment by Yusufras** [comment]
I made some changes. I changed the AND to &
I changed the et.al. to _italics_
Did i do something wrong?

**Pull request merged**
